# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

UpdateB_BMD <- function(X, Y, A, B, pvec, nrank, d, lam, maxit, eps, threads = 1L) {
    .Call('_iSRRR_UpdateB_BMD', PACKAGE = 'iSRRR', X, Y, A, B, pvec, nrank, d, lam, maxit, eps, threads)
}

png_quartimax <- function(X, maxit = 1000L, eps = 1e-5, al = 1.0) {
    .Call('_iSRRR_png_quartimax', PACKAGE = 'iSRRR', X, maxit, eps, al)
}

png_varimax <- function(X, maxit = 1000L, eps = 1e-5, al = 1.0) {
    .Call('_iSRRR_png_varimax', PACKAGE = 'iSRRR', X, maxit, eps, al)
}

arcov <- function(p, rho, threads = 1L, display_progress = TRUE) {
    .Call('_iSRRR_arcov', PACKAGE = 'iSRRR', p, rho, threads, display_progress)
}

